### PR TITLE
Add support for configurable section in -Tman

### PR DESCRIPTION
**Pull request by paravoid**
Fixes: #43

### CODE REVIEW

**Comment by kristapsdz** [comment]
Can you change it from `section` to `man section` (canonicalised as `mansection`)?  This makes it more in line with the conventions of multimarkdown, which uses `<format> <name>`, e.g., `latex header` canonicalised as `latexheader`. Everything else looks great!

**Comment by paravoid** [comment]
So, pandoc uses `section` for the same purpose in its metadata block. Pandoc's metadata is in YAML, so it's not directly compatible (at minimum the section needs to be enclosed by `---`), but it still may be something that matters to you, especially if we add `-M key=value` support down the line. Happy to adjust regardless, just wanted you to have all the data :)

**Comment by paravoid** [comment]
Actually, `pandoc -f markdown+mmd_title_block` or `pandoc -f markdown_mmd` is directly compatible. So perhaps it's worth keeping the same metadata key name for compatibility.

**Comment by kristapsdz** [comment]
Thanks for the research!  I've merged this as-is.

**Comment by paravoid** [comment]
Thank you!

**Pull request closed without merging**
